// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//var articledata = ArticleData.FromJson(jsonString);

namespace LinguaNews
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ArticleData
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("keywords")]
        public string[] Keywords { get; set; }

        [JsonProperty("creator")]
        public string[] Creator { get; set; }

        //[JsonProperty("video_url")]//
       // public object VideoUrl { get; set; }// *attributes not provided by free trial

        [JsonProperty("description")]
        public string Description { get; set; }

       // [JsonProperty("content")]//
       // public string Content { get; set; }//

        [JsonProperty("pubDate")]
        public DateTimeOffset PubDate { get; set; }

        [JsonProperty("full_description")]
        public string FullDescription { get; set; }

        [JsonProperty("image_url")]
        public Uri ImageUrl { get; set; }

        [JsonProperty("source_id")]
        public string SourceId { get; set; }
        public string DifficultyEstimate { get; set; } = "Unranked";
    }

    public partial class ArticleData
    {
        public static ArticleData[] FromJson(string json) => JsonConvert.DeserializeObject<ArticleData[]>(json, LinguaNews.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ArticleData[] self) => JsonConvert.SerializeObject(self, LinguaNews.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

